apiVersion: v2
name: pihole
description: Umbrella pihole chart

type: application

version: 0.1.0

appVersion: "2.27.0"

dependencies:
  - name: pihole
    version: 2.27.0
    repository: https://mojo2600.github.io/pihole-kubernetes/
