apiVersion: v2
name: longhorn
description: Umbrella longhorn chart

type: application

version: 0.1.2

appVersion: "1.7.2"

dependencies:
  - name: longhorn
    version: 1.7.2
    repository: https://charts.longhorn.io
