apiVersion: v2
name: longhorn
description: Umbrella longhorn chart

type: application

version: 0.1.1

appVersion: "1.7.0"

dependencies:
  - name: longhorn
    version: 1.7.0
    repository: https://charts.longhorn.io
