apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world
  type: LoadBalancer
  ports:
    - name: hello-world
      protocol: TCP
      port: 82
      targetPort: 80
      nodePort: 30009