apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv-local-config   # < name of the persisant volume ("pv") in kubenetes
  namespace: jellyfin            # < namespace where place the pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi                   # < max. size we reserve for the pv
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany                # < Multiple pods can write to storage 
  persistentVolumeReclaimPolicy: Retain # < The persistent volume can reclaimed 
  local:
    path: /storage01/jellyfin
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv-local-data   # < name of the persisant volume ("pv") in kubenetes
  namespace: jellyfin            # < namespace where place the pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Gi                   # < max. size we reserve for the pv
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany                # < Multiple pods can write to storage 
  persistentVolumeReclaimPolicy: Retain # < The persistent volume can reclaimed 
  local:
    path: /storage01/data