apiVersion: v1
kind: Service
metadata:
  name: redis-server-loadbalancer
  namespace: redis-server
spec:
  type: LoadBalancer
  selector:
    app: redis-server
  ports:
    - port: 6379
      targetPort: 80